### ISSUE TITLE
Can not run org-alert related command in spacemacs

### ISSUE THREAD

**Issue by everiori** [spegoraro/org-alert#12]
I tried two ways:
1. Add org-alert as additional-package in spacemacs
2. M-x to install the package from melpa

By both way, I can not run org-alert related functions such as org-alert-check with M-x.
I am not so sure what did I miss. Please help.

**Comment by spegoraro** [comment]
I don't use spacemacs but from what I understand using `additional-package` only ensures the package is downloaded, it doesn't load it at all. You still need to use: `(require 'org-alert)`. 
Same applies to melpa.

**Comment by everiori** [comment]
Thanks for the explanation, I added (require 'org-alert) to user-config function of spacemacs, and it works now.

**Comment by Moanrisy** [comment]
Thanks, after add require it work too
