### ISSUE TITLE
org-alert disrupts minibuffer interactions

### ISSUE THREAD

**Issue by dustinlacewell-wk** [spegoraro/org-alert#13]
I'm finding that I would like org-alert to run quite frequently. However, this has brought to my attention a behavior wherein the point is moved from the minibuffer to the org-mode buffer. I assume this is because org-alert is moving the point to the buffer in order to calculate whether any alerts need to be shown. But it seems that it is not successful at restoring the position to the minibuffer if it is trying to do so.

**Comment by spegoraro** [comment]
Hi, thanks for posting the issue.

@PierreTechoueyres has generously created #16 to resolve this but it has one issue remaining before I can merge it.

**Comment by spegoraro** [comment]
#16 has been merged and resolves the minibuffer disruption issue.
