### ISSUE TITLE
Add support for external alert program

### ISSUE THREAD

**Issue by mankoff** [spegoraro/org-alert#2]
I'd like to be able to use this with the "terminal-notifier" program on OS X so I get the alerts even when not in emacs. Is this possible? Can you add it to a FAQ?

**Comment by spegoraro** [comment]
It's based on the [alert package](https://github.com/jwiegley/alert) which supports terminal-notifier. I haven't used it myself but setting the style to 'notifier' should work:

``` elisp
(setq alert-default-style 'notifier)
```

You can see the list of all supported alert types [here](https://github.com/jwiegley/alert#builtin-alert-styles).

As for getting the alerts when not in emacs, if you're running in daemon mode this works automatically.

This is mentioned in the readme but might be a bit too far down, if it causes any more confusion I'll move the configuration section higher up.
