### ISSUE TITLE
Feature for alerts to work like Google Calendar/Outlook alerts

### ISSUE THREAD

**Issue by codygman** [spegoraro/org-alert#20]
Right now org-alert pops up notifications for each item in the org-agenda. I think it could be useful to notify when a scheduled item is coming up, maybe 15m by default but also looks for one or more `REMINDERN` properties.

It would also be convenient for my use case to have an alert on end time so I know when I should be wrapping up a task or already have finished it.

Thoughts?

**Comment by spegoraro** [comment]
Having a feature to set the number of minutes before a notification for a scheduled/deadlined item is planned (hopefully get it done in the next few days). Before I can do that I plan on cleaning up the codebase significantly by making a polyfill for the `org-map-entries` function in #17 for users of org < 9.

Once this is done then it will become trivial to modify the behaviour of notifications to add the functionality you want.

**Comment by ntBre** [comment]
I meant to comment on this earlier, but I think the package now has at least part of this feature. I've left it open because I would still like to implement your idea about the `REMINDERN` properties, but the notification cutoff part should work now.

**Comment by ntBre** [comment]
Finally got around to the `REMINDERN` part in bddb342.
