### ISSUE TITLE
org-alert-headline-regexp not found

### ISSUE THREAD

**Issue by AtomicNess123** [spegoraro/org-alert#23]
Hi, 

In your main page:

`org-alert searches for agenda entries with 'Sched' or 'Deadline' word by default. You can set any other regexp you wish using the org-alert-headline-regexp variable`

However, I couldn't find the variable `org-alert-headline-regexp`.

Thanks!
GM

**Comment by ntBre** [comment]
I think this should have been taken care of by #17, which eliminated this variable. The package now defines a similar `org-alert-match-string` variable though.

**Comment by AtomicNess123** [comment]
Thanks, now how would I add not just scheduled and deadlines, but any active or inactive time stamp? Thanks so much in advance for your help!

**Comment by ntBre** [comment]
@AtomicNess123 Could you send an example? I'll try to see if `org-alert-match-string` can handle that or if it will require additional functionality.

**Comment by AtomicNess123** [comment]
Sure. An active timestamp would be something like this:

```
** Send report
 <2021-09-09 Thu 20:00>
```

This is my org-alert-match-string variable:

```
org-alert-match-string is a variable defined in ‘org-alert.el’.
Its value is
"SCHEDULED>=\"<today>\"+SCHEDULED<\"<tomorrow>\"|DEADLINE>=\"<today>\"+DEADLINE<\"<tomorrow>\""

Documentation:
property/todo/tags match string to be passed to ‘org-map-entries’.

```

I do not know how to begin modifying that variable to include timestamps.
Thanks!

**Comment by ntBre** [comment]
I just added a change to address this in light of #27. There's a new variable called `org-alert-time-match-string`. If you set it to something like `"<.*\\([0-9]\\{2\\}:[0-9]\\{2\\}\\).*>"` and set `org-alert-match-string` to `nil`, org-alert will pull all of the entries in your agenda files and then check for timestamps in all of them. This is pretty bad if you have a lot of non-timestamped entries in the agenda file, but I'm not sure how to modify `org-alert-match-string` to be more precise yet either. Hopefully this helps a bit though.

**Comment by AtomicNess123** [comment]
Thanks. 
So I set the following in my init file:

```
(setq org-alert-time-match-string "<.*\\([0-9]\\{2\\}:[0-9]\\{2\\}\\).*>")
(setq org-alert-match-string nil)
```

And I run now org-alert-check but get

`helm-M-x-execute-command: Invalid use of ‘\’ in replacement text`

**Comment by ntBre** [comment]
Hmm, that's weird. I'm not sure why helm would be reading that string, but I haven't been using helm myself lately. Could you try this with helm disabled? And then could you maybe `toggle-debug-on-error` and paste the output here? org-alert is only doing regular expression matches as far as I know, so there shouldn't be any replacing unless helm is doing something weird.

**Comment by AtomicNess123** [comment]
I decided to stop using this package for the moment. Thanks anyway.
