### ISSUE TITLE
Are PRs welcome?

### ISSUE THREAD

**Issue by z3t0** [spegoraro/org-alert#24]
Hi, first of all thank you so much for writing this package! Also the code is so nicely written and organized... I was able to figure out how it works and make changes very easily!

I have an idea to filter out tasks that have a timestamp later in the day. This avoids showing deadlines or scheduled items that are at 10pm if its only 5pm right now.

I am happy to write a PR for this but just wanted to know if this project is still actively accepting them? I ask because I'm sure you have many other responsibilities so I don't want to just automatically expect you to take on the burden of reviewing and merging whatever code random people on the internet send haha.

Alternatively, I could fork but would prefer to help improve the upstream library!

**Comment by ntBre** [comment]
PRs are welcome! I just pushed some changes that I think address your suggestion, but if not, feel free to submit a PR.
