### ISSUE TITLE
Configurable alert cutoff for each entry

### ISSUE THREAD

**Issue by pataquets** [spegoraro/org-alert#30]
Having a single default cutoff for every entry does not work in some cases.
Eg: 10m may be enough time for an online meeting, but it won't cut it if you have an in-person meeting at the other end of the city and you have to drive.
AFAIK, there is not such a property to set the cutoff time different than the scheduled time.

**Comment by ntBre** [comment]
I totally agree, I think this is why I've left #20 open too. I've been meaning to look into this, but I'd be glad to accept a PR for it if you want to give it a try.

**Comment by ntBre** [comment]
I think I handled this in bddb342. I used the suggested property name from #20 (`REMINDERN`), but also added a variable `org-alert-cutoff-prop` so that you can set your own. Give it a try and let me know if you run into any issues!

**Comment by pataquets** [comment]
That's great, @ntBre. Thank you!
The customizable property name it's a smart addition.
Tip for those using [akhramov/org-wild-notifier.el](https://github.com/akhramov/org-wild-notifier.el): the property name should be `WILD_NOTIFIER_NOTIFY_BEFORE`.
Also, I'm afraid you forgot to cross out the last item in [the readme's TODO section](https://github.com/spegoraro/org-alert#todos) :grin:

**Comment by ntBre** [comment]
No problem, thanks for the suggestion! Ahh, good catch on the readme. I'll delete that TODO and add what you said about org-wild-notifier too. Thanks again!
