### ISSUE TITLE
Notifications for inactive timestamp not respect org-alert-notify-cutoff

### ISSUE THREAD

**Issue by Cletip** [spegoraro/org-alert#33]
Hello !
I suspect a behavior that is not normal : when you have an event with SCHEDULED and a date + hour, the notification will appear all the day, and not respect the variable org-alert-notify-cutoff.
Try with this :

* TODO A notification
SCHEDULED: [2023-10-07 Sat 21:55]
And do org-alert-check !

Thanks in advance for your answer

**Comment by ntBre** [comment]
Could you confirm your org-alert version? I can't reproduce this locally.

I saved the following in `/tmp/try.org`:

```org
* TODO a notification
  SCHEDULED: <2023-10-08 Sun 11:31>
```

And then ran this code:

```elisp
(let ((org-agenda-files '("/tmp/try.org"))
      (org-alert-notify-cutoff 5))
  (org-alert-check))
```

At 11:23, the cutoff value of 5 does not show a notification for me, but a value of 10 does, as I would expect.

What you're describing is the behavior of the package before I started maintaining it, but any version after 5758aa5 in August 2021 should obey the cutoff.

I also see that your date is surrounded by square brackets instead of angle brackets, but when I change mine to square brackets, nothing is shown at all.

**Comment by Cletip** [comment]
Thanks for your answer :)

Ok, so I do have weird behaviour: I have notifications with inactive timestamps (with "[]") 

To summarise, I did this
- run emacs -q
- copy and past alert and org-alert into a buffer, evaluate
- eval this :
  (setq org-agenda-files '("/tmp/try.org")
	org-alert-notify-cutoff 10
	alert-default-style 'libnotify
	)
- and then, in try.org :

```
Now, it's 10:30.

* TODO a notification
SCHEDULED: [2023-10-09 Mon. 11:00]
```

Finally, I did org-alert-check (at 10:30)... I have the notification, no matter what time of day it is.

On the other hand, when I switch to active timestamp, the behaviour is normal.

I suspect that is (maybe) the emacs version (because I did emacs -q, and I still get this error, whereas for you, everything works fine), so here's mine :
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-05-31

I don't know why I have this behavior :(

PS : to complete this weird behavior, I did this :
Set alert-default-style to value 'message
And then, I org-alert-check when **I must have the notification**. I have this in the *Message* buffer :

Timestamp is now active
10:40: a notification
Timestamp is now inactive
a notification

It's not the same display.

To finish, when **I must not have the notification** and I do org-alert-check, I always get the notification when I have an inactive timestamp.

I'm trying to find some clues, maybe it's just useless ^^.

**Comment by ntBre** [comment]
Can you show your value of `org-alert-match-string` and `org-alert-time-match-string`? Like I said, I didn't get any notifications for the inactive timestamp case. My value for `org-alert-match-string` is `"SCHEDULED<\"<yesterday>\"+SCHEDULED<\"<tomorrow>\""` and I have the default value for `org-alert-time-match-string`, which is `"\\(?:SCHEDULED\\|DEADLINE\\):.*<.*\\([0-9]\\{2\\}:[0-9]\\{2\\}\\).*>"`.

To get it to match inactive timestamps, I'm assuming you've modified this second variable. Probably if you left out a capture group, something is going wrong [here](https://github.com/spegoraro/org-alert/blob/ae0527626cf8d1ab7c27980ba86d657c595bdeef/org-alert.el#L145), although I would actually expect an error to bubble up somewhere if this were the case.

**Comment by ntBre** [comment]
Sorry, I guess I ignored that you were doing `emacs -q`, so you must not be modifying these variables. Let me see if I can reproduce this with `-q` too.

**Comment by ntBre** [comment]
Sorry for the delay. I can reproduce this with `emacs -q`, so I can start debugging it now.

**Comment by ntBre** [comment]
I can also reproduce this with my own config if I paste in the default value for `org-alert-match-string` instead of `"SCHEDULED<\"<yesterday>\"+SCHEDULED<\"<tomorrow>\""` like I sent before. With what I sent before and have in my config, I don't get the notification, so you can try that in the meantime!

**Comment by ntBre** [comment]
I just pushed a fix, but you may also  need to change your `org-alert-time-match-string` to something like ` "\\(?:SCHEDULED\\|DEADLINE\\):.*\\(?:\\[\\|<\\).*\\([0-9]\\{2\\}:[0-9]\\{2\\}\\).*\\(?:\\]\\|>\\)"` to match the inactive time stamps. I'm pretty sure without the bug I just fixed inactive timestamps would not be matched!
