### ISSUE TITLE
How do deal with all-day tasks?

### ISSUE THREAD

**Issue by anonimno1** [spegoraro/org-alert#34]
Hello all,

in my workflow I have 2 types of tasks:

* TODO Task1
SCHEDULED: <2023-10-28 Sat>
* TODO Task2
SCHEDULED: <2023-10-28 Sat 09:00>

Task1 can be done during the day, time doesn't matter. Task2 has to be done at 09:00.

My org-alert setup is this:

(use-package org-alert
    :ensure t
    :custom (alert-default-style 'notifications)
    :config
    (setq org-alert-interval 300
          org-alert-notify-after-event-cutoff 1
          org-alert-notification-title "Org Reminder")
    (org-alert-enable))

So this works great for Task2, I get notified when it's approaching and the notifications stop 1min after 9 o'clock.
But for Task1 I get repeated notifications every 300s. I would like to get notified once, e.g. on startup of emacs or at some fixed time of day, but then it should stop. How do I go configuring this?

Thank you!

**Comment by ntBre** [comment]
Hmm, I'm not sure there's a perfect way to do this currently. The simplest fix is just marking Task1 DONE when you don't want to be notified about it anymore. Or you could assign it a time one hour in the future so it will remind you again later (basically snoozing it). 

You can also play with the `REMINDERN` property discussed in the README if you want it to notify you once some pre-defined amount of time ahead like 3 hours. Both of these would require assigning it a time. Does any of that sound workable?

A specific daily notification type sounds handy, but I'm not sure how we would actually keep track of having sent a notification without the state of the TODO changing.

**Comment by anonimno1** [comment]
Hi,

so some sort of workaround is needed. I try basically adding hour stamp on them, something generic like 06:00 (usually I do not do stuff at that time :)).
Thank you for the answer.

**Comment by ntBre** [comment]
No problem! You may also want to change the value of `org-alert-notify-after-event-cutoff` to make sure you see the notification. Otherwise if you start Emacs after that cutoff (or the alert fades) you might miss your notification! At least I think that's how it works. I hope these workarounds get you something that works. If not, please let us know

**Comment by zcjava** [comment]
> No problem! You may also want to change the value of `org-alert-notify-after-event-cutoff` to make sure you see the notification. Otherwise if you start Emacs after that cutoff (or the alert fades) you might miss your notification! At least I think that's how it works. I hope these workarounds get you something that works. If not, please let us know

i have the problem. this task is not time,becase not need specific time do it at schedual day . how can ignore alert it by set some config

**Comment by zcjava** [comment]
> > No problem! You may also want to change the value of `org-alert-notify-after-event-cutoff` to make sure you see the notification. Otherwise if you start Emacs after that cutoff (or the alert fades) you might miss your notification! At least I think that's how it works. I hope these workarounds get you something that works. If not, please let us know
> 
> i have the problem. this task is not time,becase not need specific time do it at schedual day . how can ignore alert it by set some config

ony alert have a timestamp in schedual , or alert one time  in schedual whole day

**Comment by ntBre** [comment]
@zcjava I may not be following your issue exactly, but I think the best workaround is still to assign a time to the task even if it doesn't really have a set time. That's pretty much just how org-alert works currently. After you see the notification the first time, you can mark it as DONE and not get any more notifications that day.

**Comment by zcjava** [comment]
> @zcjava I may not be following your issue exactly, but I think the best workaround is still to assign a time to the task even if it doesn't really have a set time. That's pretty much just how org-alert works currently. After you see the notification the first time, you can mark it as DONE and not get any more notifications that day.

ok. org-alert cannot  ignore alert the TODO item by set some config for it .  i konw . i try it.

**Comment by ntBre** [comment]
Ohhh, you want to ignore the notification? But still have a time stamp? You could probably set the `REMINDERN` property to something very high. It's supposed to be used to change the alert cutoff, but I think if you set it to something greater than 24 hours it might prevent a notification at all. You could also try making `org-alert-match-string` more specific if you'd rather annotate your agenda entries in some way.
