### ISSUE TITLE
alert-osx-notifier-notify: AppleScript error

### ISSUE THREAD

**Issue by zcjava** [spegoraro/org-alert#35]
i use it , but tip the error in mac. when i use alert package (alert "message") , it work good.  can u fixed it

**Comment by ntBre** [comment]
This sounds like an [alert](https://github.com/jwiegley/alert) issue not org-alert. Could you provide a bit more information? I don't even have a Mac to test anything on.

**Comment by zcjava** [comment]
ok, thanks . i change termianl-message .
