### ISSUE TITLE
Feature Request: Direct Navigation to Heading from Notification Click

### ISSUE THREAD

**Issue by Cletip** [spegoraro/org-alert#36]
Hello,

I'm currently using the org-alert package for notifications in org-mode and I'm greatly appreciative of its functionality ! However, I have a feature request that could enhance the user experience.

Is there a way to implement a feature where, upon clicking a notification, the user is taken directly to the specific heading related to that notification in org-mode ? This would greatly streamline the process of managing tasks and notes, especially when dealing with multiple notifications.
The main problem for me is that depend (maybe I think) of the variable alert-default-style. For me, the main concern is the style with libnotify and terrmux.

Thank you for considering this feature request.

**Comment by ntBre** [comment]
That's a great idea! Unfortunately I don't think libnotify supports that, at least from a cursory look in the past. I would be glad to be wrong, though. Or interested in another notification method that could provide such actions!

**Comment by ntBre** [comment]
I'm going to go ahead and close this for now. I think this is mostly up to the notification program itself, as far as I understand the problem. If org-alert needs to add support for one of those that provides this behavior, I'd be glad to look into it. 

The rest are just a few notes for me or anyone else looking into this in the future. I did another search today for "clickable notifications linux" and found these two links interesting:

https://unix.stackexchange.com/questions/545888/setup-notify-send-click-action
https://bbs.archlinux.org/viewtopic.php?id=172965

I can't figure out how to get the `dunstify` answer on the second one to do anything useful, and I also can't figure out how to use the `--action` flag on `notify-send` from the manual. Either way, we simply call into [alert](https://github.com/jwiegley/alert) for our notifications, so there would have to be support for

1. Clickable notifications at the OS/desktop environment level
2. A way to pass these into and back out of `alert`
3. An interface to these in org-alert

For this to work at all. Here we're obviously only concerned with 3, so we'd need 1 and 2 covered before we can do anything to help.
