### ISSUE TITLE
Change `defvar` to `defcustom`?

### ISSUE THREAD

**Issue by rennsax** [spegoraro/org-alert#38]
Hi, would you mind preferring `defcustom` than `defvar` for customizable variables, so the user can find them in the Customization UI?

**Comment by ntBre** [comment]
Sure, I didn't even think about that! That should just be a simple substitution for all of the variables right, or are there other implications I'm not considering?

**Comment by rennsax** [comment]
Hi, I create the PR #39. Reviews are welcome!

**Comment by ntBre** [comment]
Just merged #39, so closing this one. Thanks again!
