### ISSUE TITLE
`org-alert-check': (void-variable org-agenda-buffer-name)

### ISSUE THREAD

**Issue by pseudomyne** [spegoraro/org-alert#5]
Hi. any idea why i get  Error running timer `org-alert-check': (void-variable org-agenda-buffer-name) ?
I don't get the error when the agenda buffer is opened. does that mean i need to have an opened agenda buffer to make org-alert work ?

**Comment by spegoraro** [comment]
Hi, I've just merged #4 which resolves this issue. I had mistakenly assumed that org-agenda would have been required already so the variable wasn't present.
