### ISSUE TITLE
How to enable at startup ?

### ISSUE THREAD

**Issue by pseudomyne** [spegoraro/org-alert#6]
hi. i'm not a lisper and cannot enable org-alert at startup. Tried  (org-alert-enable) in my dotfile with no success. thanks for your help. Well, it might have worked nevertheless... seems alert has displayed after 300s...

**Comment by spegoraro** [comment]
Hi there, 300s is the default interval at which it will check your agenda and send notifications. If you want to change it (to 150s for example) just `(setq org-alert-interval 150)` in your `init.el`.

**Comment by pseudomyne** [comment]
Hey Steve, hmm, seems i still need to manually M-x (org-alert-enable) at startup to get the alerts, but I may have something wrong somewhere.

**Comment by spegoraro** [comment]
Ok, could you please post the section of your init file where you load org-alert?

**Comment by pseudomyne** [comment]
oh, i'm so sorry. Did not write (setq org-alert-enable t) with correct syntax. Thank you for org-alert.
