### ISSUE TITLE
org-alert "unnarrow" subtree during org-alert-check

### ISSUE THREAD

**Issue by AlexanderMamonov** [spegoraro/org-alert#9]
Hello,

org-alert cancels effect of org-narrow-subtree during org-alert-check.
It looks like because of call org-agenda-list.
Do you have any idea, how to fix it?

**Comment by spegoraro** [comment]
Hi @AlexanderMamonov, thanks for the report, I'll look into it this evening and see if I can have it return the buffer to the narrowed state.
